### ISSUE TITLE
Change columns property syntax to more readable

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#22]
Most probably we need to brainstorm a new syntax for custom responsive steps.

The current one is "funny" and "WAT". It's hard to read and interpret it.

(This is the DX tests finding)

**Comment by limonte** [comment]
Add two simpler examples before the current one.

**Comment by jouni** [comment]
Current syntax: `1, 30em 2 labels-on-top, 40em 2, 50em 3 labels-on-top`

Possible alternatives, should run a quick hallway test with these to gather opinions:
- `1; 30em 2 labels-on-top; 40em 2; 50em 3 labels-on-top`
- `1 / 30em 2 labels-on-top / 40em 2 / 50em 3 labels-on-top`

Or, alternatively, open up the property as a JSON object:
```javascript
formLayout.columns = [
{
  threshold: "0",
  columns: 1,
  labelsOnTop: false
},
{
  threshold: "30em",
  columns: 2,
  labelsOnTop: true
},
{
  threshold: "40em",
  columns: 2,
  labelsOnTop: false
},
{
  threshold: "50em",
  columns: 3,
  labelsOnTop: true
}];
```

**Comment by limonte** [comment]
JSON looks understandable right away without reading any docs :+1:

**Comment by jouni** [comment]
Yeah, but writing it’s quite impossible to write that declaratively in HTML, and would force the developer to add JavaScript to control the layout.

My initial wish was that this could be controlled with CSS, something like:

```css
.my-form {
  --vaadin-form-layout-column-threshold: 0, 30em, 40em, 50em;
  --vaadin-form-layout-column-count: 1, 2, 2, 3;
  --vaadin-form-layout-column-labels: aside, top, aside, top;
  
  /* Or with a shorthand, similarly to the current syntax */
  --vaadin-form-layout-columns: 1, 30em 2 top, 40em 2, 50em 3 top;
}
```

But we can’t really observe the changes for those properties. I guess we could listen to mutation changes on the whole DOM tree and check if anything changed, but we thought that might be a bit overkill at least initially.
